<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>DxwSyncOverlay</RootNamespace>
    <AssemblyName>SyncOverlay</AssemblyName>
    <EnableComHosting>true</EnableComHosting>
    <RegisterForComInterop>true</RegisterForComInterop>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
  </ItemGroup>
</Project>
